# See COPYRIGHT file at the top of the source tree.
"""Metric and specification definitions for the LSST Validate framework.
"""

try:
    # version.py is auto-generated by sconsUtils
    from .version import *  # noqa: F401,F403
except:
    __version__ = "unknown"
